# Generated by Django 3.0.8 on 2021-10-27 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Street')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='City')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='District')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='State')),
                ('pincode', models.CharField(blank=True, max_length=10, verbose_name='Pincode')),
                ('faculty_employees', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Faculty Employees')),
            ],
            options={
                'verbose_name': 'Faculty Address',
                'verbose_name_plural': 'Faculty Addresses',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AvailablePincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(blank=True, max_length=10, verbose_name='Pincode')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Faculty', verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'Available Pincode',
                'verbose_name_plural': 'Available Pincodes',
                'ordering': ['-id'],
            },
        ),
    ]
