# Generated by Django 3.0.8 on 2021-10-30 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='District')),
                ('pincode', models.CharField(blank=True, max_length=10, verbose_name='Pincode')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Faculty', verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'Available Destination',
                'verbose_name_plural': 'Available Destinations',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='AvailablePincode',
        ),
    ]
