# Generated by Django 3.0.8 on 2021-11-01 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20211102_0011'),
        ('general', '0005_auto_20211101_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledestination',
            name='delivery_boys',
            field=models.ForeignKey(blank=True, limit_choices_to={'user__groups__name': 'Delivery Boy'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.StaffUser', verbose_name='Available Delivery Boys'),
        ),
    ]
