# Generated by Django 3.0.8 on 2021-11-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20211102_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabledestination',
            name='delivery_boys',
        ),
    ]
