# Generated by Django 3.0.8 on 2021-10-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourierAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(blank=True, max_length=200, verbose_name='House Number')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Street')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='City')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='District')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='State')),
                ('pincode', models.CharField(blank=True, max_length=10, verbose_name='Pincode')),
            ],
            options={
                'verbose_name': 'Courier Address',
                'verbose_name_plural': 'Courier Addresses',
                'ordering': ['-id'],
            },
        ),
    ]
