# Generated by Django 3.0.8 on 2021-10-17 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Parcle Title')),
                ('description', models.TextField(blank=True, default='NO DESCRIPTION', null=True, verbose_name='Parcle Description')),
                ('weight', models.FloatField(verbose_name='Parcle Weight')),
                ('charge', models.FloatField(blank=True, null=True, verbose_name='Charge')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Recipient Name')),
                ('recipient_email', models.CharField(max_length=200, verbose_name='Recipient Email')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='Parcle Register Date')),
                ('delivary_start_date', models.DateField(blank=True, null=True, verbose_name='Delivery Start Date')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Delivery Rating')),
                ('feedback', models.TextField(blank=True, default='NO FEEDBACK', null=True, verbose_name='Delivery Feedback')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer User')),
                ('deliver_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipent_address', to='courier.CourierAddress', verbose_name='Recipient Address')),
                ('pickup_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_address', to='courier.CourierAddress', verbose_name='Pickup Address')),
            ],
            options={
                'verbose_name': 'Courier',
                'verbose_name_plural': 'Couriers',
                'ordering': ['-id'],
            },
        ),
    ]
