# Generated by Django 3.0.8 on 2021-11-01 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courier', '0005_auto_20211101_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierdeliverystatus',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Delivery Boy'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivary_boy', to=settings.AUTH_USER_MODEL, verbose_name='Delivery Boy'),
        ),
    ]
