# Generated by Django 3.0.8 on 2021-11-02 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0006_auto_20211102_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='deliver_address',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='pickup_address',
        ),
        migrations.AddField(
            model_name='courieraddress',
            name='courier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courier.Courier', verbose_name='Courier Details'),
            preserve_default=False,
        ),
    ]
