# Generated by Django 3.0.8 on 2021-11-02 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_remove_availabledestination_delivery_boys'),
        ('courier', '0008_deliveraddress_pickupaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierdeliverystatus',
            name='shipping_center',
        ),
        migrations.AddField(
            model_name='courierdeliverystatus',
            name='deliver_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deliver_faculty', to='general.Faculty', verbose_name='Deliver Faculty'),
        ),
        migrations.AddField(
            model_name='courierdeliverystatus',
            name='pickup_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pick_up_faculty', to='general.Faculty', verbose_name='Pick Up Faculty'),
        ),
        migrations.DeleteModel(
            name='CourierAddress',
        ),
    ]
