# Generated by Django 3.0.8 on 2021-11-03 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0009_auto_20211102_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='delivary_start_date',
            new_name='pickup_date',
        ),
    ]
