# Generated by Django 3.0.8 on 2021-11-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0012_courierdeliverystatus_conform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierdeliverystatus',
            name='conform',
        ),
        migrations.AddField(
            model_name='courier',
            name='conform',
            field=models.BooleanField(default=False),
        ),
    ]
