# Generated by Django 3.0.8 on 2021-11-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0013_auto_20211106_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierdeliverystatus',
            name='is_picked',
            field=models.BooleanField(default=False, verbose_name='Courier Picked Up'),
        ),
    ]
