# Generated by Django 3.0.8 on 2021-10-27 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211017_2233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailablePincode',
        ),
    ]
