# Generated by Django 3.0.8 on 2021-11-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_staffuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffuser',
            old_name='join_data',
            new_name='date_join',
        ),
        migrations.RenameField(
            model_name='staffuser',
            old_name='leave_data',
            new_name='date_leave',
        ),
    ]
