# Generated by Django 3.0.8 on 2021-11-01 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('user', '0008_auto_20211101_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
