# Generated by Django 3.0.8 on 2021-11-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20211102_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='work',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Work'),
        ),
    ]
