# Generated by Django 3.0.8 on 2021-11-01 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20211102_0028'),
        ('user', '0010_auto_20211102_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Faculty', verbose_name='Member of Faculty'),
        ),
    ]
