# Generated by Django 3.0.8 on 2021-11-02 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_remove_availabledestination_delivery_boys'),
        ('user', '0013_staffuser_delivery_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='faculty',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='general.Faculty', verbose_name='Member of Faculty'),
        ),
    ]
